### PR TITLE
HasCurrencies trait, refactoring & exception fixes

### PR DESCRIPTION
**Pull request by tjbp**
Have swapped the logic between getByCode() and getByAlpha3() for consistency (shouldn't make any difference externally). Additionally I've corrected the Exception usage (InvalidArgumentException is for invalid argument types, rather than invalid formats; and OutOfBoundsException is a more specific child of RuntimeException.

I've also added a trait for use in classes, as well as info on using it to the readme.

### CODE REVIEW

**Comment by alcohol** [comment]
I can agree on the changing of what kind of Exception to use (unfortunately this does require upping the major version since it is an API change that is not BC).

 Moving the logic around has no advantage nor disadvantage, so, I'm neutral in regards to that. 

I do not agree with adding the trait though. A user can implement it on their end if they need it. Proper dependency injection would be a better solution though.

**Comment by tjbp** [comment]
Understood on the trait, probably best not to add clutter. What do you mean by proper dep injection? Adding a setter to the trait for injecting the object (`public method setISO4217(ISO4217 $iso4217);`) would do that, or do you mean roping in a dep injection lib?

**Comment by alcohol** [comment]
Best way to inject dependencies is via the constructor method of the class that depends on the subject. How you inject it there can be through a number of ways, none of which are really relevant to this PR :-)

**Comment by alcohol** [comment]
Took your first commit, but fast-forwarded it instead of merge-commit, sorry. Anyway, thanks for your contribution :-)

**Pull request closed without merging**
